export const NEXT_PUBLIC_SITE_URL = process.env.NEXT_PUBLIC_SITE_URL;
export const NEXT_PUBLIC_TURNSTILE_SITE_KEY =
  process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY;
export const NEXT_PUBLIC_CAP_INSTANCE_URL =
  process.env.NEXT_PUBLIC_CAP_INSTANCE_URL;
export const NEXT_PUBLIC_CAP_SITE_KEY = process.env.NEXT_PUBLIC_CAP_SITE_KEY;
